// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU2pYkxOb-bOBmLMv6qj6YDMGWHO3N0sI',
    appId: '1:785323482922:web:661865a38ab64ad258c853',
    messagingSenderId: '785323482922',
    projectId: 'noteapp-ed479',
    authDomain: 'noteapp-ed479.firebaseapp.com',
    storageBucket: 'noteapp-ed479.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU2pYkxOb-bOBmLMv6qj6YDMGWHO3N0sI',
    appId: '1:785323482922:android:661865a38ab64ad258c853',
    messagingSenderId: '785323482922',
    projectId: 'noteapp-ed479',
    storageBucket: 'noteapp-ed479.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU2pYkxOb-bOBmLMv6qj6YDMGWHO3N0sI',
    appId: '1:785323482922:ios:661865a38ab64ad258c853',
    messagingSenderId: '785323482922',
    projectId: 'noteapp-ed479',
    storageBucket: 'noteapp-ed479.appspot.com',
    iosBundleId: 'com.note.app.noteApp',
  );
}
